[project]
name = 'Decentralized-Specialized-Educational-Accessibility-Resources'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.adaptation-tracking]
path = 'contracts/adaptation-tracking.clar'
clarity_version = 2
epoch = 2.5

[contracts.effectiveness-assessment]
path = 'contracts/effectiveness-assessment.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
